### ISSUE TITLE
Server crash after unloading an extension if it is used by plugins.

### ISSUE THREAD

**Issue by fxss-repository** [nefarius/sm-ext-socket#5]
Server crash after unloading an extension.
If the extension at the time of unloading use - 100% crash.

Crash always happens when you turn off the server.

OS: Windows 7 Ultimate
Extension Version - 3.0.1
Server - TF2.

**Comment by FAUSheppy** [comment]
Nobody will be able to debug this without a stacktrace.

**Comment by nefarius** [comment]
I'm just hosting this, I have no insights anymore whatsoever 😛
